/*
 * Copyright (c) 2013 Samsung Electronics Co., Ltd All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __TIZEN_SECURITY_PRIVILEGE_INFO_TYPES_H
#define __TIZEN_SECURITY_PRIVIELGE_INFO_TYPES_H

#include <tizen.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum _privilegeGroup
{
	_PRV_GROUP_1,
	_PRV_GROUP_2,
	_PRV_GROUP_3,
	MAX_PRV_GROUP,
} privilegeGroup;

#define EXTRA_GROUP MAX_PRV_GROUP - 1

typedef struct
{
	const char* privilege;
	const char* name_string_id;
	const char* description_string_id;
	const char* privilege_level;
	privilegeGroup privilege_group_enum;

} privilege_info_s;

typedef struct
{
	const char* privilege;
	const char* name_string_id;
	const char* description_string_id;
	privilegeGroup privilege_group_enum;

} external_privilege_info_s;

typedef struct
{
	const char* privilege_group;
	privilegeGroup privilege_group_enum;
	const char* name_string_id;

} privilege_group_info_s;

typedef struct
{
	int privilege_group;
	privilege_info_privileges_cb callback;
	void* user_data;
} privilege_list_cb_data;

const static privilege_group_info_s privilege_group_info_table[MAX_PRV_GROUP] =
{
	{"http://tizen.org/privilege/group1", _PRV_GROUP_1, "IDS_PRIVILEGE_GROUP_NAME1"},
	{"http://tizen.org/privilege/group2", _PRV_GROUP_2, "IDS_PRIVILEGE_GROUP_NAME2"},
	{"http://tizen.org/privilege/group3", _PRV_GROUP_3, "IDS_PRIVILEGE_GROUP_NAME3"},
};

#define PRIVILEGE_NUM 123

const static privilege_info_s privilege_info_table[PRIVILEGE_NUM] =
{
	{"http://tizen.org/privilege/account.read", "IDS_ST_BODY_READING_ACCOUNTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_ACCOUNTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/account.write", "IDS_ST_BODY_MANAGING_ACCOUNTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CREATE_UPDATE_AND_DELETE_ACCOUNTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/alarm", "IDS_ST_BODY_SETTING_ALARMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SET_AN_ALARM_AND_WAKE_THE_DEVICE_UP_AT_THE_SCHEDULED_TIME", _PRV_GROUP_1},
	{"http://tizen.org/privilege/antivirus", "IDS_ST_BODY_SCANNING_FOR_VIRUSES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_ANTIVIRUS_APPLICATION_TO_SCAN_FOR_HARMFUL_CONTENT", _PRV_GROUP_1},
	{"http://tizen.org/privilege/application.kill", "IDS_ST_BODY_CLOSING_APPLICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CLOSE_ANOTHER_APPLICATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/application.launch", "IDS_ST_BODY_OPENING_APPLICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_BE_OPENED_CONDITIONALLY_OR_TO_OPEN_ANOTHER_APPLICATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/application.read", "IDS_ST_BODY_READING_APPLICATION_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_APPLICATION_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appmanager.certificate", "IDS_ST_BODY_GETTING_APPLICATION_CERTIFICATES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_GET_SPECIFIED_APPLICATION_CERTIFICATES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appmanager.kill", "IDS_ST_BODY_CLOSING_APPLICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CLOSE_ANOTHER_APPLICATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appmanager.launch", "IDS_ST_BODY_MANAGING_APPLICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_ANOTHER_APPLICATION_OPENING_CONDITIONALLY", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appsetting", "IDS_ST_BODY_MANAGING_APPLICATION_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_APPLICATION_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appusage", "IDS_ST_BODY_RECEIVING_APPLICATION_USAGE_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_NOTIFICATIONS_ABOUT_FOREGROUND_APPLICATION_CHANGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/appwidgetprovider.install", "IDS_ST_BODY_INSTALLING_DYNAMIC_BOX_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ADD_DYNAMIC_BOX_TO_THE_HOME_SCREEN", _PRV_GROUP_1},
	{"http://tizen.org/privilege/audiomanager.route", "IDS_ST_BODY_MANAGING_AUDIO_ROUTES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SET_AUDIO_INPUT_AND_OUTPUT_ROUTES_AND_RECEIVE_NOTIFICATIONS_ABOUT_ROUTE_EVENTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/audiorecorder", "IDS_ST_BODY_RECORDING_AUDIO_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_AUDIO_RECORDING", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetooth.admin", "IDS_ST_BODY_MANAGING_BLUETOOTH_GENERAL_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_BLUETOOTH_SETTINGS_MSG", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetooth.gap", "IDS_ST_BODY_USING_BLUETOOTH_GAP_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_GENERIC_ACCESS_PROFILE_HGAP_FOR_EXAMPLE_TO_SCAN_FOR_AND_PAIR_DEVICES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetooth.health", "IDS_ST_BODY_USING_BLUETOOTH_HDP_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_HEALTH_DEVICE_PROFILE_HHDP_FOR_EXAMPLE_TO_SEND_HEALTH_DATA", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetooth.opp", "IDS_ST_BODY_USING_BLUETOOTH_OPP_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_OBJECT_PUSH_PROFILE_HOPP_FOR_EXAMPLE_TO_SEND_FILES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetooth.spp", "IDS_ST_BODY_USING_BLUETOOTH_SPP_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_SERIAL_PORT_PROFILE_HSPP_FOR_EXAMPLE_TO_SEND_SERIAL_DATA", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bluetoothmanager", "IDS_ST_BODY_MANAGING_BLUETOOTH_SYSTEM_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_BLUETOOTH_SYSTEM_SETTINGS_RELATED_TO_PRIVACY_AND_SECURITY_MSG", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bookmark.read", "IDS_ST_BODY_READING_BOOKMARKS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_BOOKMARKS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/bookmark.write", "IDS_ST_BODY_MANAGING_BOOKMARKS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CREATE_UPDATE_AND DELETE_BOOKMARKS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/calendar.read", "IDS_ST_BODY_READING_CALENDAR_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ SCHEDULE_AND_TASK_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/calendar.write", "IDS_ST_BODY_MANAGING_CALENDAR_M_NOUN", "IDS_TPLATFORM_BODY_ALLOWS_THE_APPLICATION_TO_CREATE_UPDATE_AND_DELETE_SCHEDULE_AND_TASK_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/callforward", "IDS_ST_BODY_FORWARDING_CALLS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CONTROL_THE_CALL_FORWARDING_SERVICE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/callhistory.read", "IDS_ST_BODY_READING_CALL_LOGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_CALL_LOGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/callhistory.write", "IDS_ST_BODY_MANAGING_CALL_LOGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CREATE_UPDATE_AND_DELETE_CALL_LOGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/camera", "IDS_ST_BODY_USING_CAMERA_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_DEVICE_CAMERAS_TO_PREVIEW_AND_CAPTURE_PICTURES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/cellbroadcast", "IDS_ST_BODY_MANAGING_CELL_BROADCAST_SERVICE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_THE_CELL_BROADCAST_SERVICE_HCBS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/certificate.read", "IDS_ST_BODY_READING_CERTIFICATES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_CERTIFICATES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/certificate.write", "IDS_ST_BODY_MANAGING_CERTIFICATES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ADD_UPDATE_AND_DELETE_CERTIFICATES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/contact.read", "IDS_ST_BODY_READING_CONTACTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_CONTACTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/contact.write", "IDS_ST_BODY_MANAGING_CONTACTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ADD_UPDATE_AND_DELETE_CONTACTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/content.read", "IDS_ST_BODY_READING_CONTENT_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_CONTENT", _PRV_GROUP_1},
	{"http://tizen.org/privilege/content.write", "IDS_ST_BODY_MANAGING_CONTENT_M_NOUN", "IDS_TPLATFORM_BODY_ALLOWS_THE_APPLICATION_TO_CREATE_UPDATE_AND_DELETE_CONTENT", _PRV_GROUP_1},
	{"http://tizen.org/privilege/customnetaccount", "IDS_ST_BODY_USING_ADVANCED_INTERNET_OPTIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_INTERNET_WITH_A_SPECIFIED_BEARER", _PRV_GROUP_1},
	{"http://tizen.org/privilege/datacontrol.consumer", "IDS_ST_BODY_ACCESSING_EXPORTED_DATA_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_SPECIFIC_DATA_EXPORTED_BY_OTHER_APPLICATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/datasync", "IDS_ST_BODY_SYNCING_DEVICE_DATA_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SYNCHRONISE_DEVICE_DATA_TO_THE_SERVER_USING_THE_OMA_DS_12_PROTOCOL", _PRV_GROUP_1},
	{"http://tizen.org/privilege/dns", "IDS_ST_BODY_PROVIDING_DNS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_PROVIDE_THE_DOMAIN_NAME_SERVICE_HDNS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/download", "IDS_ST_BODY_DOWNLOADING_VIA_HTTP_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_HTTP_DOWNLOADS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/drmservice", "IDS_ST_BODY_MANAGING_DRM_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_DIGITAL_RIGHTS_MANAGEMENT_HDRM_LICENCES_AND_RETRIEVE_DRM_CONTENT_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/filesystem.read", "IDS_ST_BODY_READING_FILE_SYSTEMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_FILE_SYSTEMS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/filesystem.write", "IDS_ST_BODY_WRITING_TO_FILE_SYSTEMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_WRITE_TO_FILE_SYSTEMS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/fullscreen", "IDS_ST_BODY_CHANGING_TO_FULL_SCREEN_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_FULL_SCREEN", _PRV_GROUP_1},
	{"http://tizen.org/privilege/geolocationpermission.read", "IDS_ST_BODY_READING_GEOLOCATION_PERMISSIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_GEOLOCATION_PERMISSIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/geolocationpermission.write", "IDS_ST_BODY_MANAGING_GEOLOCATION_PERMISSIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_DELETE_GEOLOCATION_PERMISSIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/http", "IDS_ST_BODY_COMMUNICATING_WITH_THE_HTTP_SERVER_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_COMMUNICATE_WITH_THE_HTTP_SERVER", _PRV_GROUP_1},
	{"http://tizen.org/privilege/ime", "IDS_ST_BODY_PROVIDING_INPUT_METHODS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_PROVIDE_A_WAY_TO_INPUT_CHARACTERS_AND_SYMBOLS_INTO_AN_ASSOCIATED_INPUT_FIELD", _PRV_GROUP_1},
	{"http://tizen.org/privilege/imemanager", "IDS_ST_BODY_MANAGING_INPUT_METHODS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_THE_INSTALLED_INPUT_METHODS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/inputmanager", "IDS_ST_BODY_MANAGING_INPUT_EVENTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_GENERATE_TOUCH_AND_KEY_EVENTS_AND_CAPTURE_SCREENS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/internet", "IDS_ST_BODY_ACCESSING_INTERNET_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_THE_INTERNET", _PRV_GROUP_1},
	{"http://tizen.org/privilege/location", "IDS_ST_BODY_USING_USER_LOCATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_USER_LOCATION_DATA", _PRV_GROUP_1},
	{"http://tizen.org/privilege/lockmanager", "IDS_ST_BODY_UNLOCKING_DEVICE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_UNLOCK_THE_DEVICE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/log", "IDS_ST_BODY_USING_LOG_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_SYSTEM_LOG_HDLOG", _PRV_GROUP_1},
	{"http://tizen.org/privilege/mediacapture", "IDS_ST_BODY_RECORDING_VIDEO_AND_AUDIO_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_VIDEO_RECORDING_AND_AUDIO_RECORDING_WITH_CAMERA_OR_AUDIO_RECORDER", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.email", "IDS_ST_BODY_SENDING_EMAILS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SEND_EMAIL_MESSAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.mms", "IDS_ST_BODY_SENDING_MMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SEND_MMS_MESSAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.read", "IDS_ST_BODY_ACCESSING_MESSAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_MESSAGES_AND_RETRIEVE_MESSAGES_FROM_THE_MESSAGE_BOXES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.send", "IDS_ST_BODY_SENDING_MESSAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SEND_SMS_MMS_AND_EMAIL_MESSAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.sms", "IDS_ST_BODY_MANAGING_SMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SEND_AND_RECEIVE SMS_MESSAGES_AND_RETRIEVE_SMS_MESSAGES_FROM_THE_SMS_MESSAGE_BOXES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/messaging.write", "IDS_ST_BODY_WRITING_MESSAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_WRITE_SMS_MMS_AND_EMAIL_MESSAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/netstatisticsmanager", "IDS_ST_BODY_RESETTING_NETWORK_STATISTICS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RESET_NETWORK_STATISTICS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/network.account", "IDS_ST_BODY_MANAGING_NETWORK_ACCOUNTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_NETWORK_ACCOUNTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/network.connection", "IDS_ST_BODY_MANAGING_NETWORK_CONNECTIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_NETWORK_CONNECTIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/network.statistics", "IDS_ST_BODY_READING_NETWORK_STATISTICS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_NETWORK_STATISTICS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/network.statistics.read", "IDS_ST_BODY_READING_NETWORK_STATISTICS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_NETWORK_STATISTICS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/networkbearerselection", "IDS_ST_BODY_SELECTING_NETWORK_CONNECTION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_REQUEST_RELEASE_A_SPECIFIC_NETWORK_CONNECTION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/networkmanager", "IDS_ST_BODY_UPDATING_NETWORK_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_UPDATE_SYSTEM_NETWORK_ACCOUNTS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/nfc.admin", "IDS_ST_BODY_MANAGING_NFC_GENERAL_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_NFC_SETTINGS_SUCH_AS_TURNING_NFC_ON_OR_OFF", _PRV_GROUP_1},
	{"http://tizen.org/privilege/nfc.common", "IDS_ST_BODY_USING_NFC_COMMON_FEATURES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_NFC_COMMON_FEATURES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/nfc.p2p", "IDS_ST_BODY_PUSHING_NFC_MESSAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_PUSH_NFC_MESSAGES_TO_OTHER_DEVICES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/nfc.tag", "IDS_ST_BODY_READING_WRITING_TO_NFC_TAGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_AND_WRITE_NFC_TAG_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/nfcmanager", "IDS_ST_BODY_MANAGING_NFC_SYSTEM_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_NFC_SYSTEM_SETTINGS_MSG", _PRV_GROUP_1},
	{"http://tizen.org/privilege/notification", "IDS_ST_BODY_PROVIDING_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_PROVIDE_USER_NOTIFICATIONS_SUCH_AS_MESSAGES_AND_BADGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/notification.read", "IDS_ST_BODY_READING_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_GET_NOTIFICATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/notification.write", "IDS_ST_BODY_UPDATING_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_UPDATE_NOTIFICATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/notificationmanager", "IDS_ST_BODY_MANAGING_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_NOTIFICATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/package.info", "IDS_ST_BODY_RECEIVING_PACKAGE_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_PACKAGE_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/packageinfo", "IDS_ST_BODY_RECEIVING_PACKAGE_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_PACKAGE_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/packagemanager.info", "IDS_ST_BODY_RECEIVING_DETAILED_PACKAGE_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_DETAILED_PACKAGE_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/packagemanager.install", "IDS_ST_BODY_MANAGING_PACKAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_INSTALL_OR_UNINSTALL_APPLICATION_PACKAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/packagemanager.setting", "IDS_ST_BODY_MANAGING_PACKAGE_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SET_PACKAGE_CONFIGURATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/packagesetting", "IDS_ST_BODY_MANAGING_PACKAGE_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_SET_PACKAGE_CONFIGURATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/platforminfo", "IDS_ST_BODY_READING_PLATFORM_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_INFORMATION_SUCH_AS_THE_PLATFORM_OR_API_VERSION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/power", "IDS_ST_BODY_MANAGING_POWER_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_HOLD_AND_CONTROL_POWER_STATES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/privacymanager.read", "IDS_ST_BODY_READING_PRIVACY_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/privacymanager.write", "IDS_ST_BODY_MANAGING_PRIVACY_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/privilegemanager.read", "IDS_ST_BODY_READING_PRIVILEGE_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO READ_PRIVILEGE_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/push", "IDS_ST_BODY_RECEIVING_PUSH_NOTIFICATIONS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_PUSH_NOTIFICATIONS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/se", "IDS_ST_BODY_ACCESSING_SECURE_ELEMENTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_TOSECURE_SMART_CARD_CHIP_SUCH_AS_UICC_SIM_EMBEDDED_SECURE_ELEMENT_OR_SECURE_SD_CARD", _PRV_GROUP_1},
	{"http://tizen.org/privilege/secureelement", "IDS_ST_BODY_ACCESSING_SECURE_ELEMENTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_TOSECURE_SMART_CARD_CHIP_SUCH_AS_UICC_SIM_EMBEDDED_SECURE_ELEMENT_OR_SECURE_SD_CARD", _PRV_GROUP_1},
	{"http://tizen.org/privilege/setting", "IDS_ST_BODY_ACCESSING_USER_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_UPDATE_OR_READ_USER_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/settingmanager.read", "IDS_ST_BODY_READING_SYSTEM_SECURITY_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_SECURITY_OR_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/settingmanager.write", "IDS_ST_BODY_MANAGING_SYSTEM_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_SECURITY_OR_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/shortcut.install", "IDS_ST_BODY_MANAGING_SHORTCUTS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ADD_AND_REMOVE_SHORTCUTS_FROM_THE_HOME_SCREEN", _PRV_GROUP_1},
	{"http://tizen.org/privilege/smstrigger", "IDS_ST_BODY_RECEIVING_PORT_SPECIFIC_SMS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RECEIVE_SMS_MESSAGES_FROM_A_SPECIFIED_PORT", _PRV_GROUP_1},
	{"http://tizen.org/privilege/socket", "IDS_ST_BODY_COMMUNICATING_WITH_OTHER_DEVICES_AND_SERVERS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_COMMUNICATE_WITH_OTHER_DEVICES_AND_SERVERS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/system", "IDS_ST_BODY_READING_SYSTEM_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_SYSTEM_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/systeminfo", "IDS_ST_BODY_ACCESSING_SYSTEM_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RETRIEVE_SYSTEM_INFORMATION_SUCH_AS_NETWORK_SIM_AND_CALL_DETAILS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/systemmanager", "IDS_ST_BODY_READING_SECURE_SYSTEM_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_SECURE_SYSTEM_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/systemsetting.read", "IDS_ST_BODY_READING_SYSTEM_SECURITY_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ_SECURITY_OR_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/systemsetting.write", "IDS_ST_BODY_MANAGING_SYSTEM_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CHANGE_SECURITY_OR_PRIVACY_SETTINGS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/telephony", "IDS_ST_BODY_ACCESSING_TELEPHONY_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_RETRIEVE_TELEPHONY_INFORMATION_SUCH_AS_NETWORK_SIM_AND_CALL_DETAILS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/telephonymanager", "IDS_ST_BODY_CONFIGURING_MOBILE_NETWORKS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_CONFIGURE_THE_MOBILE_NETWORKS", _PRV_GROUP_1},
	{"http://tizen.org/privilege/testautomation", "IDS_ST_BODY_USING_TEST_AUTOMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_THE_TEST_AUTOMATION_FEATURE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/time", "IDS_ST_BODY_ACCESSING_TIME_AND_DATE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_GET_TIME_AND_DATE_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/tizen", "IDS_ST_BODY_USING_COMMON_MODULE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_TIZEN_WEB_DEVICE_API_COMMON_MODULE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/uimanager", "IDS_ST_BODY_MANAGING_USER_INTERFACE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_UI_PROPERTIES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/unlimitedstorage", "IDS_ST_BODY_ACCESSING_UNLIMITED_STORAGE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_USE_ATTACHED_STORAGE_WITHOUT_SIZE_LIMITATIONS_FOR_DB_OR_FILES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/useridentity", "IDS_ST_BODY_ACCESSING_USER_ID_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_ACCESS_PRIVACY_INFORMATION_FOR_USER_IDENTIFICATION_PURPOSES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/userprofile.read", "IDS_ST_BODY_READING_USER_PROFILE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_READ THE_USER_PROFILE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/userprofile.write", "IDS_ST_BODY_MANAGING_USER_PROFILE_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE THE_USER_PROFILE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/vibrator", "IDS_ST_BODY_MANAGING_VIBRATION_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_TURN_ON_AND_USE_VIBRATE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/videorecorder", "IDS_ST_BODY_RECORDING_VIDEO_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_VIDEO_RECORDING_WITH_THE_CAMERA", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wappush", "IDS_ST_BODY_MANAGING_WAP_PUSH_MESSAGES_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_WAP_PUSH_MESSAGES", _PRV_GROUP_1},
	{"http://tizen.org/privilege/web.privacy", "IDS_ST_BODY_MANAGING_WEB_DATA_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_THE_USER_DATA_STORED_BY_THE_WEB_CONTROL_OR_BROWSER", _PRV_GROUP_1},
	{"http://tizen.org/privilege/web.service", "IDS_ST_BODY_ACCESSING_WEB_CONTENT_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_DISPLAY_WEB_CONTENT_OR_USE_THE_WEB_CONTENT_RELATED_API", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wifi.admin", "IDS_ST_BODY_MANAGING_WI_FI_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_WI_FI_ON_THE_DEVICE_SUCH_AS_TURNING_WI_FI_ON_OR_OFF_AND_CONNECTING_TO_AP", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wifi.read", "IDS_ST_BODY_READING_WI_FI_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_REQUEST_WI_FI_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wifi.wifidirect.admin", "IDS_ST_BODY_MANAGING_WI_FI_DIRECT_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_WI_FI_DIRECT_ON_THE_DEVICE", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wifi.wifidirect.read", "IDS_ST_BODY_READING_WI_FI_DIRECT_INFORMATION_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_REQUEST_WI_FI_DIRECT_INFORMATION", _PRV_GROUP_1},
	{"http://tizen.org/privilege/wifimanager", "IDS_ST_BODY_MANAGING_WI_FI_SYSTEM_SETTINGS_M_NOUN", "IDS_ST_BODY_ALLOWS_THE_APPLICATION_TO_MANAGE_THE_WI_FI_SYSTEM_SETTINGS_SUCH_AS_UPDATING_AP_INFORMATION", _PRV_GROUP_1},
};

#define EXTERNAL_PRIVILEGE_NUM 0

const static privilege_info_s external_privilege_info_table[EXTERNAL_PRIVILEGE_NUM] =
{
	//	{"http://privilege", "IDS_PRIVILEGE_NAME_ID", "IDS_PRIVILEGE_DESC_ID", "platform", _PRV_GROUP_ENUM},
};

#ifdef __cplusplus
}
#endif

#endif // __TIZEN_SECURITY_PRIVACY_INFO_TYPES_H
